#! /bin/sh

IFS=$'\n' MONITORS=($(bspc query -M))

# Pointer Configuration
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

# Monitor Configuration
bspc monitor ${MONITORS[0]} -d Web Games Apps

# Border Colors
bspc config normal_border_color '#000000'
bspc config focused_border_color '#6673a3'

# Window Gap Configuration
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config -m ${MONITORS[1]} window_gap 0
bspc config -m ${MONITORS[0]} window_gap 0
bspc config -m ${MONITORS[0]} top_padding 30

# Application Rules
bspc rule -a feh state=floating
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a vlc state=pseudo_tiled
bspc rule -a Vlc state=pseudo_tiled
bspc rule -a steam desktop='^2' follow=off
bspc rule -a firefox state=pseudo_tiled desktop='^1' follow=on
bspc rule -a discord desktop='^2' follow=off
bspc rule -a Pavucontrol desktop='^1' follow=on state=floating
bspc rule -a Alacritty border=off follow=on desktop='^4'
bspc rule -a News follow=on monitor=${MONITORS[0]} state=pseudo_tiled private=on rectangle=1200x1080+0+0
bspc rule -a Browse follow=on state=floating private=on rectangle=1400x800+580+320
bspc rule -a MPlayer monitor='^1' state=floating private=on border=off follow=on rectangle=800x600+1400+40
