#! /bin/sh

IFS=$'\n' MONITORS=($(bspc query -M))

# Pointer Configuration
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

# Monitor Configuration
bspc monitor ${MONITORS[0]} -d Web Games Apps

# Border Colors
bspc config normal_border_color '#000000'
bspc config focused_border_color '#6673a3'

# Window Gap Configuration
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config -m ${MONITORS[1]} window_gap 0
bspc config -m ${MONITORS[0]} window_gap 0
bspc config -m ${MONITORS[0]} top_padding 30

# Application Rules
bspc rule -a feh state=floating
bspc rule -a vlc state=pseudo_tiled
bspc rule -a Vlc state=pseudo_tiled
bspc rule -a Steam desktop='^2' follow=off
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a calibre desktop='^3' follow=off
bspc rule -a discord desktop='^2' follow=off
bspc rule -a Blueman-manager follow=on state=floating
bspc rule -a Pavucontrol desktop='^1' follow=on state=floating
bspc rule -a "dolphin-emu:Dolphin" desktop='^2' follow=off state=floating hidden
bspc rule -a "dolphin-emu:Faster Melee - Slippi (2.1.1)" desktop='^2' follow=on state=fullscreen
bspc rule -a steam_proton desktop='^2' follow=off state=floating
bspc rule -a calibre-ebook-viewer desktop='^3' follow=on state=floating
bspc rule -a Alacritty border=off follow=on
bspc rule -a "bg3.exe" locked=on
bspc rule -a News follow=on monitor='${MONITORS[0]}' state=pseudo_tiled private=on rectangle=1200x1080+0+0
bspc rule -a Browse follow=on monitor='${MONITORS[0]}' state=floating private=on rectangle=2000x1250+1000+1000
bspc rule -a "zoom:zoom" desktop='^2' follow=on state=floating
bspc rule -a "zoom:Zoom - Free Account" desktop='^2' follow=on state=floating
bspc rule -a "zoom:Zoom Meeting" desktop='^2' follow=on state=floating
bspc rule -a MPlayer monitor='^1' state=floating private=on border=off follow=on rectangle=800x600+1400+40
