name: home
root: ~/
tmux_options: -f ~/.config/tmux.conf
windows:
  - main:
      layout: 2604,284x83,0,0{203x83,0,0,0,80x83,204,0[80x27,204,0,2,80x27,204,28,3,80x27,204,56,4]}
      panes:
        - weechat
        - gotop -l minimal
        - ncspot
        - pulsemixer
  - code:
      panes:
        -
