" Name:         Revan
" Description:  Template for the Revan color scheme
" Author:       Michael Phillips <michaeljoelphillips@gmail.com>
" Maintainer:   Michael Phillips <michaeljoelphillips@gmail.com>
" Website:      michaelphillips.dev
" License:      Public domain
" Last Updated: Sat 23 Oct 2021 04:34:25 PM CDT

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'revan'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#2c2c2c', '#df5e6c', '#8698e1', '#e5ad58', '#5860a9', '#886db2', '#6673a3', '#c0cbdd', '#6e6e6e', '#ba063b', '#8da6f2', '#f6b007', '#3a407e', '#a285d0', '#8c8ddf', '#c0cbdd']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#c0cbdd guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c0cbdd guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
    hi Terminal guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  endif
  hi ColorColumn guibg=#3c3c3c gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi CursorColumn guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi CursorLine guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi CursorLineNr guifg=#6e6e6e guibg=#2c2c2c gui=NONE cterm=NONE
  hi DiffAdd guifg=#8698e1 guibg=#3c3c3c gui=NONE cterm=NONE
  hi DiffChange guifg=#886db2 guibg=#3c3c3c gui=NONE cterm=NONE
  hi DiffDelete guifg=#df5e6c guibg=#3c3c3c gui=NONE cterm=NONE
  hi DiffText guifg=#8c8ddf guibg=#3c3c3c gui=bold cterm=bold
  hi Directory guifg=#8698e1 guibg=#2c2c2c gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#6e6e6e guibg=#2c2c2c gui=NONE cterm=NONE
  hi ErrorMsg guifg=#df5e6c guibg=#2c2c2c gui=reverse cterm=reverse
  hi FloatBorder guifg=#c0cbdd guibg=#3c3c3c gui=NONE cterm=NONE
  hi FoldColumn guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi Folded guifg=#6e6e6e guibg=#3c3c3c gui=italic cterm=italic
  hi IncSearch guifg=#c0cbdd guibg=#2c2c2c gui=standout cterm=reverse
  hi LineNr guifg=#6e6e6e guibg=#2c2c2c gui=NONE cterm=NONE
  hi MatchParen guibg=#6e6e6e gui=NONE cterm=NONE
  hi ModeMsg guifg=#886db2 guibg=#2c2c2c gui=NONE cterm=NONE
  hi MoreMsg guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi NonText guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi Pmenu guifg=#c0cbdd guibg=#3c3c3c gui=NONE cterm=NONE
  hi PmenuSbar guifg=#6e6e6e guibg=#6e6e6e gui=NONE cterm=NONE
  hi PmenuSel guifg=#c0cbdd guibg=#5860a9 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#c0cbdd guibg=#5860a9 gui=NONE cterm=NONE
  hi Question guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi Search guifg=#c0cbdd guibg=#5860a9 gui=NONE cterm=NONE
  hi SignColumn guifg=#886db2 guibg=#2c2c2c gui=NONE cterm=NONE
  hi SpecialKey guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi SpellBad gui=underline cterm=underline
  hi SpellCap gui=underline cterm=underline
  hi SpellLocal gui=underline cterm=underline
  hi SpellRare gui=underline cterm=underline
  hi StatusLine guifg=#c0cbdd guibg=#3c3c3c gui=NONE cterm=NONE
  hi StatusLineNC guifg=#2c2c2c guibg=#6e6e6e gui=NONE cterm=NONE
  hi TabLine guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi TabLineFill guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi TabLineSel guifg=#886db2 guibg=#2c2c2c gui=NONE cterm=NONE
  hi Title guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi VertSplit guifg=#886db2 guibg=#2c2c2c gui=NONE cterm=NONE
  hi Visual guifg=#c0cbdd guibg=#3c3c3c gui=NONE cterm=NONE
  hi VisualNOS guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi WarningMsg guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi WildMenu guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi Comment guifg=#6e6e6e guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#886db2 guibg=NONE gui=bold cterm=bold
  hi Error guifg=#df5e6c guibg=#2c2c2c gui=NONE cterm=NONE
  hi Identifier guifg=#8698e1 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#6e6e6e guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e5ad58 guibg=#2c2c2c gui=NONE cterm=NONE
  hi Special guifg=#886db2 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#df5e6c guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e5ad58 guibg=#3c3c3c gui=NONE cterm=NONE
  hi Type guifg=#e5ad58 guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=#df5e6c guibg=NONE gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#2c2c2c gui=NONE cterm=NONE
  hi ToolbarButton guifg=#c0cbdd guibg=#2c2c2c gui=bold cterm=bold
  hi Exception guifg=#df5e6c guibg=#2c2c2c gui=NONE cterm=NONE
  hi Keyword guifg=#df5e6c guibg=#2c2c2c gui=NONE cterm=NONE
  hi String guifg=#a285d0 guibg=#2c2c2c gui=NONE cterm=NONE
  hi phpInclude guifg=#e5ad58 guibg=#2c2c2c gui=NONE cterm=NONE
  hi phpMemberSelector guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi phpComparison guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi phpParent guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi phpVarSelector guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi phpOperator guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi GitGutterAdd guifg=#5860a9 guibg=#2c2c2c gui=bold cterm=bold
  hi GitGutterChange guifg=#886db2 guibg=#2c2c2c gui=bold cterm=bold
  hi GitGutterDelete guifg=#df5e6c guibg=#2c2c2c gui=bold cterm=bold
  hi TSException guifg=#df5e6c guibg=#2c2c2c gui=NONE cterm=NONE
  hi TSPunctBracket guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi TSPunctDelimiter guifg=#c0cbdd guibg=#2c2c2c gui=NONE cterm=NONE
  hi TSLabel guifg=#e5ad58 guibg=#2c2c2c gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=251 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=251 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=251 ctermbg=236 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=251 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermbg=237 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=251 ctermbg=236 cterm=NONE
  hi CursorColumn ctermfg=251 ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=251 ctermbg=236 cterm=NONE
  hi CursorLineNr ctermfg=242 ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=104 ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=97 ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=237 cterm=NONE
  hi DiffText ctermfg=104 ctermbg=237 cterm=bold
  hi Directory ctermfg=104 ctermbg=236 cterm=NONE
  hi EndOfBuffer ctermfg=242 ctermbg=236 cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=236 cterm=reverse
  hi FloatBorder ctermfg=251 ctermbg=237 cterm=NONE
  hi FoldColumn ctermfg=251 ctermbg=236 cterm=NONE
  hi Folded ctermfg=242 ctermbg=237 cterm=italic
  hi IncSearch ctermfg=251 ctermbg=236 cterm=reverse
  hi LineNr ctermfg=242 ctermbg=236 cterm=NONE
  hi MatchParen ctermbg=242 cterm=NONE
  hi ModeMsg ctermfg=97 ctermbg=236 cterm=NONE
  hi MoreMsg ctermfg=251 ctermbg=236 cterm=NONE
  hi NonText ctermfg=251 ctermbg=236 cterm=NONE
  hi Pmenu ctermfg=251 ctermbg=237 cterm=NONE
  hi PmenuSbar ctermfg=242 ctermbg=242 cterm=NONE
  hi PmenuSel ctermfg=251 ctermbg=61 cterm=NONE
  hi PmenuThumb ctermfg=251 ctermbg=61 cterm=NONE
  hi Question ctermfg=251 ctermbg=236 cterm=NONE
  hi Search ctermfg=251 ctermbg=61 cterm=NONE
  hi SignColumn ctermfg=97 ctermbg=236 cterm=NONE
  hi SpecialKey ctermfg=251 ctermbg=236 cterm=NONE
  hi SpellBad cterm=underline
  hi SpellCap cterm=underline
  hi SpellLocal cterm=underline
  hi SpellRare cterm=underline
  hi StatusLine ctermfg=251 ctermbg=237 cterm=NONE
  hi StatusLineNC ctermfg=236 ctermbg=242 cterm=NONE
  hi TabLine ctermfg=251 ctermbg=236 cterm=NONE
  hi TabLineFill ctermfg=251 ctermbg=236 cterm=NONE
  hi TabLineSel ctermfg=97 ctermbg=236 cterm=NONE
  hi Title ctermfg=251 ctermbg=236 cterm=NONE
  hi VertSplit ctermfg=97 ctermbg=236 cterm=NONE
  hi Visual ctermfg=251 ctermbg=237 cterm=NONE
  hi VisualNOS ctermfg=251 ctermbg=236 cterm=NONE
  hi WarningMsg ctermfg=251 ctermbg=236 cterm=NONE
  hi WildMenu ctermfg=251 ctermbg=236 cterm=NONE
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Constant ctermfg=97 ctermbg=NONE cterm=bold
  hi Error ctermfg=167 ctermbg=236 cterm=NONE
  hi Identifier ctermfg=104 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=242 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=179 ctermbg=236 cterm=NONE
  hi Special ctermfg=97 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=179 ctermbg=237 cterm=NONE
  hi Type ctermfg=179 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=167 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=251 ctermbg=236 cterm=bold
  hi Exception ctermfg=167 ctermbg=236 cterm=NONE
  hi Keyword ctermfg=167 ctermbg=236 cterm=NONE
  hi String ctermfg=140 ctermbg=236 cterm=NONE
  hi phpInclude ctermfg=179 ctermbg=236 cterm=NONE
  hi phpMemberSelector ctermfg=251 ctermbg=236 cterm=NONE
  hi phpComparison ctermfg=251 ctermbg=236 cterm=NONE
  hi phpParent ctermfg=251 ctermbg=236 cterm=NONE
  hi phpVarSelector ctermfg=251 ctermbg=236 cterm=NONE
  hi phpOperator ctermfg=251 ctermbg=236 cterm=NONE
  hi GitGutterAdd ctermfg=61 ctermbg=236 cterm=bold
  hi GitGutterChange ctermfg=97 ctermbg=236 cterm=bold
  hi GitGutterDelete ctermfg=167 ctermbg=236 cterm=bold
  hi TSException ctermfg=167 ctermbg=236 cterm=NONE
  hi TSPunctBracket ctermfg=251 ctermbg=236 cterm=NONE
  hi TSPunctDelimiter ctermfg=251 ctermbg=236 cterm=NONE
  hi TSLabel ctermfg=179 ctermbg=236 cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi DiffText ctermfg=LightCyan ctermbg=Black cterm=bold
  hi Directory ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=Black cterm=reverse
  hi FloatBorder ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Folded ctermfg=DarkGrey ctermbg=Black cterm=italic
  hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi LineNr ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi MatchParen ctermbg=DarkGrey cterm=NONE
  hi ModeMsg ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=LightGrey ctermbg=DarkBlue cterm=NONE
  hi PmenuThumb ctermfg=LightGrey ctermbg=DarkBlue cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Search ctermfg=LightGrey ctermbg=DarkBlue cterm=NONE
  hi SignColumn ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellBad cterm=underline
  hi SpellCap cterm=underline
  hi SpellLocal cterm=underline
  hi SpellRare cterm=underline
  hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi Visual ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VisualNOS ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi Error ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi Identifier ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi Type ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Underlined ctermfg=DarkRed ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi Exception ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi Keyword ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi String ctermfg=LightMagenta ctermbg=Black cterm=NONE
  hi phpInclude ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi phpMemberSelector ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi phpComparison ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi phpParent ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi phpVarSelector ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi phpOperator ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi GitGutterAdd ctermfg=DarkBlue ctermbg=Black cterm=bold
  hi GitGutterChange ctermfg=DarkMagenta ctermbg=Black cterm=bold
  hi GitGutterDelete ctermfg=DarkRed ctermbg=Black cterm=bold
  hi TSException ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi TSPunctBracket ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TSPunctDelimiter ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TSLabel ctermfg=DarkYellow ctermbg=Black cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #2c2c2c        ~         Black
" Color: red           #df5e6c        ~         DarkRed
" Color: green         #8698e1        ~         DarkGreen
" Color: yellow        #e5ad58        ~         DarkYellow
" Color: blue          #5860a9        ~         DarkBlue
" Color: magenta       #886db2        ~         DarkMagenta
" Color: cyan          #6673a3        ~         DarkCyan
" color: orange        #ff6e01        ~         DarkRed
" Color: white         #c0cbdd        ~         LightGrey
" Color: brightblack   #6e6e6e        ~         DarkGrey
" Color: brightred     #ba063b        ~         LightRed
" Color: brightgreen   #8da6f2        ~         LightGreen
" Color: brightyellow  #f6b007        ~         LightYellow
" Color: brightblue    #3a407e        ~         LightBlue
" Color: brightmagenta #a285d0        ~         LightMagenta
" Color: brightcyan    #8c8ddf        ~         LightCyan
" Color: brightwhite   #c0cbdd        ~         White
" Color: dimblack      #3c3c3c        ~         Black
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
