#! /bin/sh

# Pointer Configuration
bspc config click_to_focus true
bspc config focus_follows_pointer false

# Monitor Configuration
bspc monitor -d Chat Web Code Games

# Border Colors
bspc config focused_border_color '#5860A9'
bspc config normal_border_color '#00000'

# Window Gap Configuration
bspc config top_padding 50
bspc config left_padding 30
bspc config right_padding 30
bspc config window_gap 20
