#! /bin/sh

# Pointer Configuration
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

# Monitor Configuration
bspc monitor 0x00C00002 -d Web Games Apps
# bspc monitor 0x00C00004 -d Term Misc

# Border Colors
bspc config normal_border_color '#000000'
bspc config focused_border_color '#5860A9'

# Window Gap Configuration
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config -m 0x00C00002 window_gap 10
bspc config -m 0x00C00004 window_gap 0
bspc config -m 0x00C00002 top_padding 30

# Application Rules
bspc rule -a feh state=floating
bspc rule -a vlc state=pseudo_tiled
bspc rule -a Vlc state=pseudo_tiled
bspc rule -a Steam desktop='^2' follow=off
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a calibre desktop='^3' follow=off
bspc rule -a discord desktop='^2' follow=off
bspc rule -a Blueman-manager follow=on state=floating
bspc rule -a Pavucontrol desktop='^1' follow=on state=floating
bspc rule -a "dolphin-emu:Dolphin" desktop='^2' follow=off state=floating hidden
bspc rule -a "dolphin-emu:Faster Melee - Slippi (2.1.1)" desktop='^2' follow=on state=fullscreen
bspc rule -a steam_proton desktop='^2' follow=off state=floating
bspc rule -a calibre-ebook-viewer desktop='^3' follow=on state=floating
bspc rule -a Alacritty border=off follow=on
