[theme]
background = "black"
primary = "white"
secondary = "white"
title = "magenta"
playing = "yellow"
playing_bg = "black"
highlight = "white"
highlight_bg = "blue"
error = "black"
error_bg = "red"
statusbar = "yellow"
statusbar_bg = "black"
statusbar_progress = "magenta"
cmdline = "white"
cmdline_bg = "black"
